import { Nunito } from "next/font/google";

import { AuthProvider } from "../contexts/AuthContext";

import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: {
        icon: "./icon.png",
        shortcut: "./shortcut-icon.png",
        apple: "./apple-icon.png",
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${nunito.className} bg-gray_five`}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
